CONTAINER Bones06
{
	NAME Bones06;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL BONES06_GLOBAL_SCALE { UNIT REAL; MIN 0.0; }
		REAL BONES06_HINGE_EXTENSION_LEFT { UNIT REAL; MIN 0.0; }
		REAL BONES06_HINGE_EXTENSION_RIGHT { UNIT REAL; MIN 0.0; }
		REAL BONES06_HINGE_THICKNESS { UNIT REAL; MIN 0.0; }
		REAL BONES06_HINGE_WRAP { UNIT REAL; MIN 0.0; }
		REAL BONES06_HINGE_ANCHOR_EXTENSION { UNIT REAL; MIN 0.0; }
	}
}
