enum
{
	ID_OBJECTPROPERTIES,
	BONES06_GLOBAL_SCALE,
	BONES06_HINGE_EXTENSION_LEFT,
	BONES06_HINGE_EXTENSION_RIGHT,
	BONES06_HINGE_THICKNESS,
	BONES06_HINGE_WRAP,
	BONES06_HINGE_ANCHOR_EXTENSION,

	// End of symbol definition
	_DUMMY_ELEMENT_
};

